apiVersion: v2
name: kratix
description: A Helm chart for installing Kratix (https://kratix.io)
type: application
version: 0.1.0
appVersion: 1.16.0
keywords:
- platform
home: https://kratix.io/
icon: https://s.giantswarm.io/app-icons/kratix/1/light.png
annotations:
  io.giantswarm.application.restrictions.cluster-singleton: 'true'
  io.giantswarm.application.restrictions.namespace-singleton: 'false'
  io.giantswarm.application.team: honeybadger
upstreamChartVersion: 0.125.0
